Integrate the Scala AST Generation with SBT
luna/enso pull request #1047
Opened 2020-07-31 07:40 UTC by Josef-Vonasek

### Pull Request Description

Closes #1005.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2020-07-31 12:27 UTC, iamrecursion requested changes
Good stuff, but a few tweaks are needed.

2020-07-31 12:27 UTC, iamrecursion commented on .gitignore
> +lib/scala/ast/src/main/scala/org/enso/ast/Ast.scala
This is going into the wrong place. It should go into a `target` folder like all generated code.

2020-07-31 12:27 UTC, iamrecursion commented on .github/workflows/scala.yml
> +  sbtVersion: 1.3.1
Why did you change the SBT version?

2020-07-31 12:27 UTC, iamrecursion commented on docs/parser/ast.md
> +Note that compared to Rust, Scala doesn't support types outside objects.
```suggestion
Note that in contrast to Rust, Scala doesn't support types outside objects.
```

2020-07-31 12:27 UTC, iamrecursion commented on build.sbt
> +val rustVersion                 = "1.40.0-nightly"
We need to make sure this is the specific nightly version we use too (b520af6fd).

2020-07-31 12:27 UTC, iamrecursion commented on build.sbt
> +    Compile / sourceGenerators += GenerateAST.task,
You need to update the contributing guide section on [rust setup](https://github.com/enso-org/enso/blob/main/docs/CONTRIBUTING.md#getting-set-up-rust) to mention that SBT will check the rust version. You should also add a link to rustup as the recommended way to install and manage toolchains. Not sure how I forgot that before.

2020-07-31 12:27 UTC, iamrecursion commented on project/GenerateAST.scala
> +    verifyRustVersion(rustVersion.value) match {
This verification should take place as part of the global `EnvironmentCheck`, rather than only when the rust generation task is triggered.

2020-07-31 12:27 UTC, iamrecursion commented on project/GenerateAST.scala
> +    * reported in stderr and rise a runtime exception.
```suggestion
    * Generates the Scala AST in the specified file. All errors are reported in 
    * stderr and raise a runtime exception.
```

2020-07-31 12:27 UTC, iamrecursion commented on lib/scala/ast/src/main/scala/org/enso/ast/Main.scala
> +package org.enso.ast
This file seems a bit pointless? Why is it here?

2020-07-31 12:27 UTC, iamrecursion commented on lib/rust/ast/src/generation.rs
> +use proc_macro2::Span;
Please fix all the lints that CI is showing in this file. You will need to view it in the files tab to see it.

2020-07-31 12:38 UTC, Josef-Vonasek commented on .github/workflows/scala.yml
> +  sbtVersion: 1.3.1
Mistake.

2020-08-03 13:20 UTC, iamrecursion approved these changes

2020-08-03 13:20 UTC, iamrecursion commented on project/GenerateAST.scala
> +
```suggestion
```

2020-08-03 14:00 UTC, merged