Rename Unit to None
luna/enso pull request #1269
Opened 2020-11-05 18:47 UTC by kustosz

### Pull Request Description
A long overdue change. `Unit` was a misnomer from the start and now it's beautiful and consistent. Also gives an option type for free.

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2020-11-05 18:52 UTC, wdanilo requested changes

2020-11-05 18:52 UTC, wdanilo commented on distribution/std-lib/Base/src/Data/Json.enso
> +None.to_json = Null
brzydkie

2020-11-05 18:54 UTC, wdanilo approved these changes

2020-11-06 11:43 UTC, iamrecursion approved these changes
LGTM! A long-overdue change.

2020-11-06 11:44 UTC, merged