Add Atom Constructor for a Module
luna/enso pull request #1375
Opened 2020-12-25 12:57 UTC by 4e6

### Pull Request Description

close #1374 

Return correct name for a module (`Test.Main` instead of `Test.Main.Main`)

Changelog:
- add: atom constructor for module

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2021-01-04 13:53 UTC, kustosz requested changes
I'm not sure why it's needed, but it definitely is not an acceptable solution. The whole point of modules being represented as atoms is that we have fewer typechecks. This solution introduces non-leaf typechecks in multiple places across the interpreter and a lot of virtual dispatch. `AtomConstructor` should be a final class (pretty much like any other runtime value in Enso).

You can implement the behavior you want just by modifying the existing `getQualifiedName` – an atom constructor is a module iff `this == getDefinitionScope().getAssociatedType()`, so just add that if.

2021-01-11 09:05 UTC, 4e6 commented
> I'm not sure why it's needed

We need to distinguish between atom and method pointers. Otherwise, we can't lookup up the method definition by the method pointer in the suggestions database, see the linked issue https://github.com/enso-org/enso/issues/1374

2021-01-11 09:30 UTC, kustosz approved these changes

2021-01-11 11:07 UTC, iamrecursion approved these changes

2021-01-11 11:29 UTC, merged