Fix code docs, add new tags to doc parser, fix `Tag.unrecognized` and braces in text.
luna/enso pull request #1452
Opened 2021-02-05 14:47 UTC by BinarySoftware

### Pull Request Description

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [ ] All code has been tested where possible.

2021-02-05 14:48 UTC, BinarySoftware commented on distribution/std-lib/Base/src/Data/Time/Date.enso
> -    ## `Date` represents a date, often viewed as year-month-day. For example,
This change was introduced because somehow starting a text with inline broke indentation on the next line, tried fixing it without success.

2021-02-08 09:54 UTC, iamrecursion requested changes

2021-02-08 09:54 UTC, iamrecursion commented on lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
> +        case object Unstable   extends Type
Please sort the list of these in the docs alphabetically, and do so here as well.

2021-02-08 09:54 UTC, iamrecursion commented on lib/scala/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
> +  """   ALAMAKOTA
Please add tests with multiple tags.

2021-02-08 10:50 UTC, iamrecursion requested changes

2021-02-08 10:50 UTC, iamrecursion commented on lib/scala/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
> +      Tags.Tag(1, Tags.Tag.Type.Private)
Please add some suffix text to these tags like the specification says is supported.

2021-02-08 11:36 UTC, iamrecursion approved these changes

2021-02-09 08:47 UTC, merged