Upgrade Graal to 21.0
luna/enso pull request #1487
Opened 2021-02-17 11:13 UTC by iamrecursion

### Pull Request Description
We use the hotfix version `21.0.0.2`.

### Important Notes

- Fixes exception handling with polyglot stuff.
- Fixes some CI issues.
- Added notes on the `add-exports` stuff.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

2021-02-17 13:19 UTC, kustosz requested changes

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
> +    thunk = new AtomConstructor("Thunk", scope).initializeFields();
This should not exist

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
> +      case Constants.THUNK:
This should not exist. It is incorrect to expect a thunk, ever. The runtime may decide to pass an evaluated value in the place of a thunk, without notice.

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
> +    unresolvedSymbol = new AtomConstructor("Unresolved_Symbol", scope).initializeFields();
This should also not exist (yet :P)

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
> +    panic = new AtomConstructor("Panic", scope).initializeFields();
This already exists.

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
> +      case Constants.UNRESOLVED_SYMBOL:
Again, this should not be assertable. A user should never expect an unresolved symbol, just a function.

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicSentinel.java
> +public class PanicSentinel extends AbstractTruffleException {
This should not be an `AbstractTruffleException` nor export the exceptions library. Notice how this makes the panic sentinels handlable in language, which is exactly opposite to what we want.

2021-02-17 13:19 UTC, kustosz commented on engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
> +// TODO [AA] 21.0.0 migration
.

2021-02-17 14:29 UTC, kustosz approved these changes

2021-02-22 11:40 UTC, radeusgd approved these changes
Looks good to me, I just have two minor questions.
Accepting conditionally on the release workflow succeeding on staging.

Also I think we need to remember to create an issue to improve the CI timing in the future, as there are places in the current workarounds that may be improved (only cleaning the instruments, avoiding additional rebuilds by only using the `build*Distribution` commands instead of `assembly` etc.)

2021-02-22 11:43 UTC, iamrecursion commented on .github/workflows/scala.yml
> -    README.md
It is. It's unused and I'm not sure why it's been around for so long!

2021-02-22 13:32 UTC, merged