Rewrite Docs Generator from Python to Scala/Java
luna/enso pull request #1729
Opened 2021-05-05 16:39 UTC by BinarySoftware

### Pull Request Description
Closes #1699 

It generates HTML files for future use in IDE, as well as Js files with tree of contents and react elements for use on website.
s
### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [ ] All code has been tested where possible.

2021-05-10 11:12 UTC, iamrecursion requested changes
Somebody else needs to review the JavaScript and CSS files.

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/DocsGeneratorMain.scala
> +  */
```suggestion
/** The entry point for the documentation generator.
  *
  * The documentation generator is responsible for creating HTML documentation for the Enso standard library. It also generates JavaScript files containing react components for the reference website.
  */
```
The text "reference website" should link to https://enso.org/docs/reference.

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/DocsGeneratorMain.scala
> +  val path = "./distribution/std-lib/Standard/src"
Nope. You're doing the same thing we discussed with the python version and hardcoding a bunch of constants. Things like this should be accepted via the command-line (using our CLI args framework), not hard-coded in the source.

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/DocsGeneratorMain.scala
> +  )
Do keep in mind that we don't actually want this rendered HTML. From the engine perspective we care about the chunks so we can assemble actually useful blocks of documentation that include extension methods, re-exports, and so on.

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/docsgenerator/DocsGenerator.scala
> +  def generate(program: String): String = {
Call this `run` given the object is `DocsGenerator`. `DocsGenerator.run` is much nicer than `DocsGenerator.generate`.

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/docsgenerator/TreeOfCommonPrefixes.scala
> +      * chooser.
```suggestion
    /** Generates an HTML tree from node, as this method is used to create the page
      * chooser.
```

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/docsgenerator/TreeOfCommonPrefixes.scala
> +  /** Groups a list of nodes by it's prefixes. Calls groupByPrefix on every node.
```suggestion
  /** Groups a list of nodes by it's prefixes.
```

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/docs-generator/src/main/scala/org/enso/docsgenerator/TreeOfCommonPrefixes.scala
> +    */
You don't need to say that it's a recursive function. Documentation is about the "why", not the "what".

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/docparser/DocParserRunner.scala
> +/** This is Doc Parser Runner.
This is useless.

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/docparser/DocParserRunner.scala
> +  //////////////////////////////////////////////////////////////////////////////
```suggestion
object DocParserRunner {

  //////////////////////////////////////////////////////////////////////////////
```

2021-05-10 11:12 UTC, iamrecursion commented on lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/docparser/DocParserRunner.scala
> +  /** This function invokes the documentation parser on every instance of
```suggestion
  //////////////////////////////////////////////////////////////////////////////
  
  /** This function invokes the documentation parser on every instance of
```

2021-05-10 20:03 UTC, BinarySoftware commented on lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/docparser/DocParserRunner.scala
> +  //////////////////////////////////////////////////////////////////////////////
Can't add 2 empty lines before section, scalafmt automatically reverts into 1 empty line between.

2021-05-11 15:27 UTC, iamrecursion requested changes

2021-05-12 15:24 UTC, BinarySoftware commented on lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/Main.scala
> +  var outDir         = "docs-js"
It needs to know where the templates are located. renamed it so it's more obvious what it is.

2021-05-13 10:57 UTC, iamrecursion approved these changes

2021-05-17 16:44 UTC, merged