Update Dockerfile for Integrating Editions with Cloud
luna/enso pull request #1848
Opened 2021-07-09 16:16 UTC by radeusgd

### Pull Request Description

Updates the Dockerfile, setting paths in such a way that the library cache (not currently implemented) and local libraries created from the IDE will persist when the cloud project is reopened.

### Important Notes

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [ ] All code has been tested where possible.

2021-07-09 16:39 UTC, lolczak requested changes
I suggest being compliant with the Linux app dir structure in the `/opt` dir:
- work dir should be in the `/opt/enso/work`
- logs dir should be in the `/opt/enso/logs`
- ensure that all necessary directories are created

2021-07-09 18:31 UTC, radeusgd commented
I've built and ran the image locally. I was able to connect to it, init the protocol connection and create an execution context.

2021-07-12 10:21 UTC, lolczak approved these changes

2021-07-12 11:17 UTC, iamrecursion approved these changes

2021-07-12 11:58 UTC, merged