Version option for Project Manager
luna/enso pull request #935
Opened 2020-06-25 10:51 UTC by lolczak

### Pull Request Description
This PR adds version option to the Project Manager runner.

### Important Notes

### Checklist
Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [ ] All code has been tested where possible.

2020-06-25 12:13 UTC, iamrecursion requested changes

2020-06-25 12:13 UTC, iamrecursion commented on lib/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
> +  private def displayVersion(): ZIO[Console, Nothing, Int] = {
This should also provide a JSON output option like runner does.

2020-06-25 14:11 UTC, 4e6 approved these changes

2020-07-01 11:01 UTC, iamrecursion approved these changes

2020-07-02 10:11 UTC, merged